### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by danialvosoughi** [erayakartuna/pdf-flipbook#4]
how can i make flip direction right to left for Persian pdfs?

**Comment by l33d4n** [comment]
@danialvosoughi RTL flip direction seems to be work by identifying the browser language. It works great with Hebrew.

You only need to add arrows positions for RTL languages:

```CSS
[dir=rtl] .directions a.prev-button {
    right: 0;
    background: #f7f6f6 url(pics/alt-next.png) no-repeat center center;
    left: auto;
}

[dir=rtl] .directions a.next-button {
    right: auto;
    background: #f7f6f6 url(pics/alt-prev.png) no-repeat center center;
    left: 0;
}
```
![image](https://user-images.githubusercontent.com/8020386/89027709-8d0bc700-d35d-11ea-8bb5-268d5ae6d722.png)
